export const T = {
  ru: {
    nav: {
      services: "Услуги",
      howItWorks: "Как работаю",
      forWhom: "Клиентам",
      products: "Продукты",
      contact: "Заявка",
    },
    hero: {
      label: "Digital Fashion Studio",
      title: "Конструирование. 3D. AI-визуализация.",
      sub: "Лекала, Tech Pack, CLO 3D и AI-каталоги для брендов и дизайнеров одежды.",
      cta: "Оставить заявку",
      ctaSub: "Ответ в течение 24 часов",
    },
    services: {
      title: "Услуги",
      sub: "От технической документации до цифровой примерки",
      items: [
        {
          num: "01", title: "Конструирование", en: "Pattern Making",
          desc: "Разработка и корректировка лекал, градация по размерной сетке, адаптация под производство.",
          result: ".dxf / .pdf комплект", price: "от 80 $", time: "3–7 дн",
          tags: ["Лекала", "Градация", "DXF/PDF"],
          color: "#c8b89a",
        },
        {
          num: "02", title: "Tech Pack", en: "Technical Documentation",
          desc: "Полный технический пакет: флэты, спецификации, BOM, таблица мерок, комментарии по пошиву.",
          result: "PDF + исходники .ai/.xlsx", price: "от 120 $", time: "5–10 дн",
          tags: ["Tech Pack", "BOM", "Flats"],
          color: "#9ab0c4",
        },
        {
          num: "03", title: "CLO 3D", en: "Digital Fitting & 3D",
          desc: "3D-моделирование изделий, цифровая примерка, корректировка посадки, визуализация коллекции.",
          result: "CLO файлы + рендеры", price: "от 150 $", time: "5–12 дн",
          tags: ["CLO 3D", "3D-рендер", "Посадка"],
          color: "#9ab89a",
        },
        {
          num: "04", title: "AI-каталог", en: "AI Catalogue & Lookbook",
          desc: "Каталожные кадры и лукбуки без фотосессии — с помощью AI-визуализации на цифровой модели.",
          result: "PNG/JPG каталог + контент", price: "от 60 $", time: "2–5 дн",
          tags: ["AI", "Лукбук", "Каталог"],
          color: "#b09ab8",
        },
        {
          num: "05", title: "Digital Avatar", en: "Virtual Model",
          desc: "Создание реалистичной цифровой модели под бренд: лицо, этничность, возраст, набор поз и эмоций.",
          result: "Аватар + позы + эмоции", price: "от 100 $", time: "3–7 дн",
          tags: ["Avatar", "Позы", "Кастомизация"],
          color: "#c8a090",
        },
      ],
      package: "Пакет «Лекала + Tech Pack + CLO 3D»",
      packagePrice: "от 350 $",
    },
    howItWorks: {
      title: "Как я работаю",
      sub: "Прозрачный процесс — от заявки до финального файла",
      steps: [
        { n: "01", label: "Заявка", desc: "Заполняешь форму — описываешь задачу, прикладываешь референсы." },
        { n: "02", label: "Бриф", desc: "Уточняю детали, задаю вопросы по посадке, ткани, размерной сетке." },
        { n: "03", label: "Работа", desc: "Конструирую, моделирую или готовлю документацию в оговорённые сроки." },
        { n: "04", label: "Результат", desc: "Передаю финальные файлы (.dxf, .pdf, CLO, PNG) через Google Drive." },
        { n: "05", label: "Follow-up", desc: "Через 7 дней уточняю, всё ли подошло, при необходимости — правки." },
      ],
    },
    forWhom: {
      title: "Для кого",
      sub: "Работаю с брендами, дизайнерами и производствами",
      clients: [
        { name: "Дизайнеры одежды", pain: "Нет времени на техдок", services: ["Tech Pack", "Лекала", "CLO 3D"], hot: true },
        { name: "Fashion-бренды", pain: "Нет бюджета на фотосессию", services: ["AI-каталог", "Аватар", "Лукбук"], hot: true },
        { name: "Маркетплейс продавцы", pain: "Нужны каталожные фото быстро", services: ["AI-каталог", "Мокапы"], hot: false },
        { name: "Швейные производства", pain: "Клиенты дают плохую документацию", services: ["Tech Pack", "Лекала"], hot: false },
        { name: "Студенты fashion", pain: "Не умеют делать Tech Pack", services: ["Шаблоны", "Гайды"], hot: false },
      ],
      formats: [
        { icon: "→", title: "Разовая", desc: "Один результат, фиксированная цена" },
        { icon: "⊞", title: "Пакет", desc: "Комплексное решение под запуск коллекции" },
        { icon: "↺", title: "Сопровождение", desc: "Ретейнер на месяц или сезон" },
        { icon: "▦", title: "Продукт", desc: "Готовые шаблоны без участия времени" },
      ],
    },
    products: {
      title: "Цифровые продукты",
      sub: "Шаблоны и ассеты для самостоятельной работы — на Gumroad и Etsy",
      comingSoon: "Скоро",
      cats: [
        { name: "Шаблоны", where: "Gumroad · Etsy", items: ["Tech Pack Template", "Measurement Sheet", "BOM Template", "Fitting Comments"] },
        { name: "Мокапы", where: "Gumroad · Creative Market", items: ["Одежда flat-lay", "Каталожные сцены", "Flat Sketches", "Fashion Graphics"] },
        { name: "Библиотеки аватаров", where: "Gumroad · CLO-SET", items: ["Digital Avatars Pack", "Позы (50+)", "Каталожные сцены", "Эмоции"] },
        { name: "Лекала PDF", where: "Gumroad · Etsy", items: ["Базовые основы", "PDF Patterns", "CLO Patterns (.zpac)"] },
      ],
    },
    contact: {
      title: "Оставить заявку",
      sub: "Опиши задачу — отвечу в течение 24 часов",
      cta: "Открыть форму заявки",
      or: "или напиши напрямую",
      socials: [
        { label: "Instagram", handle: "@3d_lastique", url: "https://instagram.com/3d_lastique" },
        { label: "Telegram", handle: "@MassSewing", url: "https://t.me/MassSewing" },
        { label: "Behance", handle: "3D Lastique", url: "https://behance.net" },
      ],
    },
    footer: {
      copy: "© 2025 3D Lastique · Digital Fashion Studio",
      tagline: "Конструирование · Tech Pack · CLO 3D · AI-визуализация",
    },
  },

  en: {
    nav: {
      services: "Services",
      howItWorks: "Process",
      forWhom: "Clients",
      products: "Products",
      contact: "Get a Quote",
    },
    hero: {
      label: "Digital Fashion Studio",
      title: "Pattern Making. 3D. AI Visualization.",
      sub: "Patterns, Tech Packs, CLO 3D, and AI catalogues for fashion brands and designers.",
      cta: "Get a Quote",
      ctaSub: "Response within 24 hours",
    },
    services: {
      title: "Services",
      sub: "From technical documentation to digital fitting",
      items: [
        {
          num: "01", title: "Pattern Making", en: "Construction",
          desc: "Pattern development and correction, grading across size ranges, adaptation for production.",
          result: ".dxf / .pdf pattern set", price: "from $80", time: "3–7 days",
          tags: ["Patterns", "Grading", "DXF/PDF"],
          color: "#c8b89a",
        },
        {
          num: "02", title: "Tech Pack", en: "Technical Documentation",
          desc: "Full tech pack: flat sketches, specifications, BOM, measurement chart, sewing notes.",
          result: "PDF + source files .ai/.xlsx", price: "from $120", time: "5–10 days",
          tags: ["Tech Pack", "BOM", "Flats"],
          color: "#9ab0c4",
        },
        {
          num: "03", title: "CLO 3D", en: "Digital Fitting & 3D",
          desc: "3D garment modelling, digital fitting, fit correction, collection visualization.",
          result: "CLO files + renders", price: "from $150", time: "5–12 days",
          tags: ["CLO 3D", "3D Render", "Fitting"],
          color: "#9ab89a",
        },
        {
          num: "04", title: "AI Catalogue", en: "AI Catalogue & Lookbook",
          desc: "Catalogue shots and lookbooks without a photoshoot — using AI visualization on a digital model.",
          result: "PNG/JPG catalogue + content", price: "from $60", time: "2–5 days",
          tags: ["AI", "Lookbook", "Catalogue"],
          color: "#b09ab8",
        },
        {
          num: "05", title: "Digital Avatar", en: "Virtual Model",
          desc: "Custom brand-ready digital model: face, ethnicity, age, pose set and emotion set.",
          result: "Avatar + poses + emotions", price: "from $100", time: "3–7 days",
          tags: ["Avatar", "Poses", "Custom"],
          color: "#c8a090",
        },
      ],
      package: "Bundle: Patterns + Tech Pack + CLO 3D",
      packagePrice: "from $350",
    },
    howItWorks: {
      title: "How I Work",
      sub: "Transparent process — from brief to final file",
      steps: [
        { n: "01", label: "Request", desc: "Fill in the form — describe your task and attach any references." },
        { n: "02", label: "Brief", desc: "I clarify details: fit, fabric, size range, and any production requirements." },
        { n: "03", label: "Work", desc: "I construct, model, or prepare documentation within the agreed timeline." },
        { n: "04", label: "Delivery", desc: "Final files (.dxf, .pdf, CLO, PNG) delivered via Google Drive." },
        { n: "05", label: "Follow-up", desc: "7 days later I check in — revisions included if needed." },
      ],
    },
    forWhom: {
      title: "Who I Work With",
      sub: "Brands, designers, and manufacturers",
      clients: [
        { name: "Fashion Designers", pain: "No time for technical docs", services: ["Tech Pack", "Patterns", "CLO 3D"], hot: true },
        { name: "Fashion Brands", pain: "No budget for a photoshoot", services: ["AI Catalogue", "Avatar", "Lookbook"], hot: true },
        { name: "Marketplace Sellers", pain: "Need catalogue photos fast", services: ["AI Catalogue", "Mockups"], hot: false },
        { name: "Garment Factories", pain: "Clients provide poor documentation", services: ["Tech Pack", "Patterns"], hot: false },
        { name: "Fashion Students", pain: "Don't know how to make a Tech Pack", services: ["Templates", "Guides"], hot: false },
      ],
      formats: [
        { icon: "→", title: "One-off", desc: "Single deliverable, fixed price" },
        { icon: "⊞", title: "Bundle", desc: "Full solution for a collection launch" },
        { icon: "↺", title: "Retainer", desc: "Monthly or seasonal collaboration" },
        { icon: "▦", title: "Product", desc: "Ready-made templates, no time required" },
      ],
    },
    products: {
      title: "Digital Products",
      sub: "Templates and assets for independent work — on Gumroad and Etsy",
      comingSoon: "Coming soon",
      cats: [
        { name: "Templates", where: "Gumroad · Etsy", items: ["Tech Pack Template", "Measurement Sheet", "BOM Template", "Fitting Comments"] },
        { name: "Mockups", where: "Gumroad · Creative Market", items: ["Clothing flat-lay", "Catalogue scenes", "Flat Sketches", "Fashion Graphics"] },
        { name: "Avatar Libraries", where: "Gumroad · CLO-SET", items: ["Digital Avatars Pack", "Poses (50+)", "Catalogue scenes", "Emotions"] },
        { name: "PDF Patterns", where: "Gumroad · Etsy", items: ["Basic blocks", "PDF Patterns", "CLO Patterns (.zpac)"] },
      ],
    },
    contact: {
      title: "Get a Quote",
      sub: "Describe your task — I'll reply within 24 hours",
      cta: "Open Request Form",
      or: "or write directly",
      socials: [
        { label: "Instagram", handle: "@3d_lastique", url: "https://instagram.com/3d_lastique" },
        { label: "Telegram", handle: "@MassSewing", url: "https://t.me/MassSewing" },
        { label: "Behance", handle: "3D Lastique", url: "https://behance.net" },
      ],
    },
    footer: {
      copy: "© 2025 3D Lastique · Digital Fashion Studio",
      tagline: "Pattern Making · Tech Pack · CLO 3D · AI Visualization",
    },
  },
};
